--liquibase formatted sql

--changeset gbabiuc:create-movie-schema splitStatements:false
CREATE SCHEMA IF NOT EXISTS movie;

--changeset gbabiuc:create-videos-table splitStatements:false
CREATE TABLE movie.videos
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    file_path   VARCHAR(255) NOT NULL,
    upload_date TIMESTAMP DEFAULT NOW()
);