--liquibase formatted sql

--changeset gbabiuc:create-users-schema splitStatements:false
CREATE SCHEMA IF NOT EXISTS users;

--changeset gbabiuc:create-users-table splitStatements:false
CREATE TABLE users.user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255)       NOT NULL,
    enabled  BOOLEAN DEFAULT TRUE
);

--changeset gbabiuc:create-roles-table splitStatements:false
CREATE TABLE users.role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

--changeset gbabiuc:create-user_roles-table splitStatements:false
CREATE TABLE users.user_role
(
    user_id BIGINT PRIMARY KEY,
    role_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES users.user (id),
    FOREIGN KEY (role_id) REFERENCES users.role (id)
);